USE DATABASE {DATABASE_NAME};
USE SCHEMA SCH_TRUSTCAB_BRONZE;

CREATE OR REPLACE TASK BRONZE_LOAD_PASSENGER_SUMMARY_TASK
WAREHOUSE='{WAREHOUSE_NAME}'
SCHEDULE='USING CRON 0 2 15 * * Asia/Kolkata'
AS
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.FACT_PASSENGER_SUMMARY');

-- Task 2: Load City Dimension
CREATE OR REPLACE TASK BRONZE_LOAD_DIM_CITY_TASK
WAREHOUSE='{WAREHOUSE_NAME}'
SCHEDULE='USING CRON 0 2 15 * * Asia/Kolkata'
AS
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.DIM_CITY');

-- Task 3: Load Repeat Trip Distribution
CREATE OR REPLACE TASK BRONZE_LOAD_REPEAT_TRIP_TASK
WAREHOUSE='{WAREHOUSE_NAME}'
SCHEDULE='USING CRON 0 2 15 * * Asia/Kolkata'
AS
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.DIM_REPEAT_TRIP_DISTRIBUTION');

-- Commented out tasks - uncomment and modify as needed:



-- Task 6: Load Monthly Target New Passengers (COMMENTED OUT)
CREATE OR REPLACE TASK BRONZE_LOAD_MONTHLY_TARGET_PASSENGERS_TASK
WAREHOUSE='{WAREHOUSE_NAME}'
SCHEDULE='USING CRON 0 2 15 * * Asia/Kolkata'
AS
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.MONTHLY_TARGET_NEW_PASSENGERS');

-- Task 7: Load Monthly Target Trips (COMMENTED OUT)
CREATE OR REPLACE TASK BRONZE_LOAD_MONTHLY_TARGET_TRIPS_TASK
WAREHOUSE='{WAREHOUSE_NAME}'
SCHEDULE='USING CRON 0 2 15 * * Asia/Kolkata'
AS
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.MONTHLY_TARGET_TRIPS');

-- Task 8: Load City Target Passenger Rating (COMMENTED OUT)
CREATE OR REPLACE TASK BRONZE_LOAD_CITY_TARGET_RATING_TASK
WAREHOUSE='{WAREHOUSE_NAME}'
SCHEDULE='USING CRON 0 2 15 * * Asia/Kolkata'
AS
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.CITY_TARGET_PASSENGER_RATING');