USE DATABASE {DATABASE_NAME};
USE SCHEMA SCH_TRUSTCAB_BRONZE;

CREATE OR REPLACE TASK BRONZE_ROOT_TASK
WAREHOUSE='WH_DEV_DATA_ENGINEER'
SCHEDULE='60 MINUTES'
AS BEGIN
CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.FACT_PASSENGER_SUMMARY');
   -- CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.DIM_CITY');
    --CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.DIM_DATE');
   -- CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.DIM_REPEAT_TRIP_DISTRIBUTION');
    --CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.FACT_TRIPS');
    --CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.MONTHLY_TARGET_NEW_PASSENGERS');
   -- CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.MONTHLY_TARGET_TRIPS');
   -- CALL TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.LOAD_FILES_FROM_EPIC_STAGE('TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT.CITY_TARGET_PASSENGER_RATING');
END;