USE DATABASE {DATABASE_NAME};
USE SCHEMA SCH_TRUSTCAB_BRONZE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
	SKIP_HEADER = 1
;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT_WITH_HEADER
	PARSE_HEADER = TRUE
	TRIM_SPACE = TRUE
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	REPLACE_INVALID_CHARACTERS = TRUE
;