-- ===================================================================
-- TRUSTCAB PROJECT - RBAC (Role-Based Access Control) IMPLEMENTATION
-- ===================================================================
-- Purpose: Implement secure, scalable RBAC for DEV environment
-- Architecture: 3-tier (Bronze/Silver/Gold) with functional roles
-- ===================================================================

-- SECTION 1: INFRASTRUCTURE SETUP
-- ===================================================================
USE ROLE SYSADMIN;

-- Create Development Database
CREATE DATABASE IF NOT EXISTS TRUSTCAB_PROD
    COMMENT = 'PRODelopment database for TRUSTCAB project - Bronze/Silver/Gold architecture';

-- Create Schema for Each Data Layer (Medallion Architecture)
CREATE SCHEMA IF NOT EXISTS TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE
    COMMENT = 'Raw/Landing zone - Bronze layer for ingested data';
    
CREATE SCHEMA IF NOT EXISTS TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER
    COMMENT = 'Transformed/Cleansed data - Silver layer for business logic';
    
CREATE SCHEMA IF NOT EXISTS TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD
    COMMENT = 'Curated/Consumption layer - Gold layer for analytics';

CREATE SCHEMA IF NOT EXISTS TRUSTCAB_PROD.CORTEX_DEMO_SCH COMMENT='Temporary schema for Cortex AI demo';

CREATE SCHEMA IF NOT EXISTS TRUSTCAB_PROD.SCH_TRUSTCAB_AUDIT COMMENT='To maintain orchestration objects';    




-- Create Dedicated Warehouses for Each Function
-- IMPROVEMENT: Consider AUTO_SUSPEND = 60 (1 minute) for PROD to save costs
CREATE WAREHOUSE IF NOT EXISTS WH_PROD_DATA_ENGINEER
    WITH WAREHOUSE_SIZE = 'XSMALL'
         MAX_CLUSTER_COUNT = 1
         SCALING_POLICY = 'ECONOMY'
         AUTO_SUSPEND = 60                -- CHANGED: Reduced from 300 to 60 seconds
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE
         COMMENT = 'Dedicated warehouse for Data Engineers - Bronze/Silver processing';

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_DATA_ANALYST
    WITH WAREHOUSE_SIZE = 'XSMALL'
         MAX_CLUSTER_COUNT = 1
         SCALING_POLICY = 'ECONOMY'
         AUTO_SUSPEND = 60                -- CHANGED: Reduced from 300 to 60 seconds
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE
         COMMENT = 'Dedicated warehouse for Data Analysts - Read-only analytics';

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_BI
    WITH WAREHOUSE_SIZE = 'XSMALL'
         MAX_CLUSTER_COUNT = 1
         SCALING_POLICY = 'ECONOMY'
         AUTO_SUSPEND = 60                -- CHANGED: Reduced from 300 to 60 seconds
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE
         COMMENT = 'Dedicated warehouse for BI tools and dashboards';

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_ETL
    WITH WAREHOUSE_SIZE = 'XSMALL'
         MAX_CLUSTER_COUNT = 1
         SCALING_POLICY = 'ECONOMY'
         AUTO_SUSPEND = 60                -- CHANGED: Reduced from 300 to 60 seconds
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE
         COMMENT = 'Dedicated warehouse for ETL processes and data pipelines';

-- ===================================================================
-- SECTION 2: ROLE HIERARCHY SETUP
-- ===================================================================
USE ROLE SECURITYADMIN;

-- Create Administrative Role for PROD Environment
CREATE ROLE IF NOT EXISTS PROD_SYSADMIN
    COMMENT = 'Administrative role for TRUSTCAB_PROD environment with full ownership';

-- Grant PROD_SYSADMIN to SYSADMIN (Role Hierarchy)
GRANT ROLE PROD_SYSADMIN TO ROLE SYSADMIN;

-- Create Functional Roles (Business Function Based)
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_ENGINEER
    COMMENT = 'Data Engineers - Full RW access to Bronze/Silver, RO to Gold';
    
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_ANALYST
    COMMENT = 'Data Analysts - Read-only access across all layers';
    
CREATE ROLE IF NOT EXISTS FR_PROD_ETL
    COMMENT = 'ETL Processes - Full RW access to Bronze/Silver, RW to Gold';
    
CREATE ROLE IF NOT EXISTS FR_PROD_BI
    COMMENT = 'BI Users - Read-only access for reporting and dashboards';

-- Grant Functional Roles to PROD_SYSADMIN (Administrative Hierarchy)
GRANT ROLE FR_PROD_DATA_ENGINEER TO ROLE PROD_SYSADMIN;
GRANT ROLE FR_PROD_DATA_ANALYST TO ROLE PROD_SYSADMIN;
GRANT ROLE FR_PROD_ETL TO ROLE PROD_SYSADMIN;
GRANT ROLE FR_PROD_BI TO ROLE PROD_SYSADMIN;

-- ===================================================================
-- SECTION 3: DATABASE ROLES (ACCESS PATTERNS)
-- ===================================================================
USE ROLE SYSADMIN;
USE DATABASE TRUSTCAB_PROD;

-- Create Access Roles (Data Layer + Permission Based)
-- RAW Layer (Bronze Schema)
CREATE DATABASE ROLE IF NOT EXISTS AR_PROD_RAW_RO
    COMMENT = 'Read-only access to Bronze/Raw layer';
CREATE DATABASE ROLE IF NOT EXISTS AR_PROD_RAW_RW
    COMMENT = 'Read-write access to Bronze/Raw layer';

-- TRANSFORMED Layer (Silver Schema)  
CREATE DATABASE ROLE IF NOT EXISTS AR_PROD_TRANS_RO
    COMMENT = 'Read-only access to Silver/Transformed layer';
CREATE DATABASE ROLE IF NOT EXISTS AR_PROD_TRANS_RW
    COMMENT = 'Read-write access to Silver/Transformed layer';

-- CURATED/CONSUMPTION Layer (Gold Schema)
CREATE DATABASE ROLE IF NOT EXISTS AR_PROD_CSM_RO
    COMMENT = 'Read-only access to Gold/Curated layer';
CREATE DATABASE ROLE IF NOT EXISTS AR_PROD_CSM_RW
    COMMENT = 'Read-write access to Gold/Curated layer';

-- ===================================================================
-- SECTION 4: ACCESS ROLE ASSIGNMENTS TO FUNCTIONAL ROLES
-- ===================================================================

-- FR_PROD_DATA_ENGINEER: RW to Bronze/Silver, RO to Gold
GRANT DATABASE ROLE AR_PROD_RAW_RW TO ROLE FR_PROD_DATA_ENGINEER;
GRANT DATABASE ROLE AR_PROD_TRANS_RW TO ROLE FR_PROD_DATA_ENGINEER;
GRANT DATABASE ROLE AR_PROD_CSM_RW TO ROLE FR_PROD_DATA_ENGINEER;   

-- FR_PROD_DATA_ANALYST: RO to All Layers
GRANT DATABASE ROLE AR_PROD_RAW_RO TO ROLE FR_PROD_DATA_ANALYST;
GRANT DATABASE ROLE AR_PROD_TRANS_RO TO ROLE FR_PROD_DATA_ANALYST;
GRANT DATABASE ROLE AR_PROD_CSM_RO TO ROLE FR_PROD_DATA_ANALYST;

-- FR_PROD_ETL: RW to All Layers (ETL processes need full pipeline access)
GRANT DATABASE ROLE AR_PROD_RAW_RW TO ROLE FR_PROD_ETL;
GRANT DATABASE ROLE AR_PROD_TRANS_RW TO ROLE FR_PROD_ETL;
GRANT DATABASE ROLE AR_PROD_CSM_RW TO ROLE FR_PROD_ETL;

-- FR_PROD_BI: RO to All Layers (Reporting and dashboards)
GRANT DATABASE ROLE AR_PROD_RAW_RO TO ROLE FR_PROD_BI;
GRANT DATABASE ROLE AR_PROD_TRANS_RO TO ROLE FR_PROD_BI;
GRANT DATABASE ROLE AR_PROD_CSM_RO TO ROLE FR_PROD_BI;

-- ===================================================================
-- SECTION 5: OWNERSHIP ASSIGNMENTS
-- ===================================================================

-- Grant Database Ownership to PROD_SYSADMIN
GRANT OWNERSHIP ON DATABASE TRUSTCAB_PROD TO ROLE PROD_SYSADMIN;

-- Grant Warehouse Ownership to PROD_SYSADMIN
GRANT OWNERSHIP ON WAREHOUSE WH_PROD_DATA_ENGINEER TO ROLE PROD_SYSADMIN;
GRANT OWNERSHIP ON WAREHOUSE WH_PROD_DATA_ANALYST TO ROLE PROD_SYSADMIN;
GRANT OWNERSHIP ON WAREHOUSE WH_PROD_BI TO ROLE PROD_SYSADMIN;
GRANT OWNERSHIP ON WAREHOUSE WH_PROD_ETL TO ROLE PROD_SYSADMIN;

-- ===================================================================
-- SECTION 6: RESOURCE MONITORING SETUP
-- ===================================================================
USE ROLE ACCOUNTADMIN;

-- Create Resource Monitors for Cost Control
-- IMPROVEMENT: Consider lower credit quotas for PRODelopment (10-20 credits)
CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROD_DATA_ENGINEER
WITH
    CREDIT_QUOTA    = 20                 -- CHANGED: Reduced from 50 to 20 for PROD
    FREQUENCY       = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = ()                    -- IMPROVEMENT: Add actual user emails
TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROD_DATA_ANALYST
WITH
    CREDIT_QUOTA    = 15                 -- CHANGED: Reduced from 50 to 15 for PROD
    FREQUENCY       = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = ()
TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROD_BI
WITH
    CREDIT_QUOTA    = 15                 -- CHANGED: Reduced from 50 to 15 for PROD
    FREQUENCY       = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = ()
TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROD_ETL
WITH
    CREDIT_QUOTA    = 25                 -- CHANGED: Reduced from 50 to 25 for PROD
    FREQUENCY       = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = ()
TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Assign Resource Monitors to Warehouses
ALTER WAREHOUSE WH_PROD_DATA_ENGINEER SET RESOURCE_MONITOR = RM_PROD_DATA_ENGINEER;
ALTER WAREHOUSE WH_PROD_DATA_ANALYST SET RESOURCE_MONITOR = RM_PROD_DATA_ANALYST;
ALTER WAREHOUSE WH_PROD_BI SET RESOURCE_MONITOR = RM_PROD_BI;
ALTER WAREHOUSE WH_PROD_ETL SET RESOURCE_MONITOR = RM_PROD_ETL;

-- ===================================================================
-- SECTION 7: WAREHOUSE PERMISSIONS
-- ===================================================================
USE ROLE SECURITYADMIN;

-- Grant Warehouse Privileges to Functional Roles
GRANT USAGE,MONITOR,OPERATE ON WAREHOUSE WH_PROD_DATA_ENGINEER TO ROLE FR_PROD_DATA_ENGINEER;
GRANT USAGE,MONITOR,OPERATE ON WAREHOUSE WH_PROD_DATA_ANALYST TO ROLE FR_PROD_DATA_ANALYST;
GRANT USAGE,MONITOR,OPERATE ON WAREHOUSE WH_PROD_BI TO ROLE FR_PROD_BI;
GRANT USAGE,MONITOR,OPERATE ON WAREHOUSE WH_PROD_ETL TO ROLE FR_PROD_ETL;

-- ===================================================================
-- SECTION 8: DATABASE AND SCHEMA LEVEL PERMISSIONS
-- ===================================================================
USE ROLE SECURITYADMIN;
USE DATABASE TRUSTCAB_PROD;

-- Database Level Permissions for RW Roles
GRANT USAGE,MONITOR ON DATABASE TRUSTCAB_PROD TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT USAGE,MONITOR ON DATABASE TRUSTCAB_PROD TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT USAGE,MONITOR ON DATABASE TRUSTCAB_PROD TO DATABASE ROLE AR_PROD_CSM_RW;

-- Schema Level Permissions - Layer Specific Access
-- Bronze Layer (Raw Data)
GRANT USAGE,MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT USAGE,MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;

-- Silver Layer (Transformed Data)
GRANT USAGE,MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT USAGE,MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;

-- Gold Layer (Curated Data)
GRANT USAGE,MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT USAGE,MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;

-- ===================================================================
-- SECTION 9: OBJECT CREATION PRIVILEGES
-- ===================================================================

-- Grant Object Creation Privileges to RW Roles
-- IMPROVEMENT: Consider granting specific privileges instead of all schemas
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE MASKING POLICY, 
      CREATE ROW ACCESS POLICY, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE,
      CREATE FILE FORMAT, CREATE STAGE, CREATE TASK 
      ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;

GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE MASKING POLICY, 
      CREATE ROW ACCESS POLICY, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE,
      CREATE FILE FORMAT, CREATE STAGE, CREATE TASK 
      ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;

GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE MASKING POLICY, 
      CREATE ROW ACCESS POLICY, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE,
      CREATE FILE FORMAT, CREATE STAGE, CREATE TASK 
      ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;

-- Database Level Permissions for RO Roles
GRANT USAGE,MONITOR ON DATABASE TRUSTCAB_PROD TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT USAGE,MONITOR ON DATABASE TRUSTCAB_PROD TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT USAGE,MONITOR ON DATABASE TRUSTCAB_PROD TO DATABASE ROLE AR_PROD_CSM_RO;

-- ===================================================================
-- SECTION 10: EXISTING OBJECTS PERMISSIONS
-- ===================================================================
USE ROLE SECURITYADMIN;
USE DATABASE TRUSTCAB_PROD;

-- AR_PROD_RAW_RW - Full Access to Bronze Layer Objects
GRANT ALL ON ALL TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL PROCEDURES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL TASKS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL SEQUENCES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL STAGES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;

-- AR_PROD_TRANS_RW - Full Access to Silver Layer Objects
GRANT ALL ON ALL TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL PROCEDURES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL TASKS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL SEQUENCES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL STAGES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;

-- AR_PROD_CSM_RW - Full Access to Gold Layer Objects
GRANT ALL ON ALL TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL PROCEDURES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL TASKS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL SEQUENCES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL STAGES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;

-- ===================================================================
-- SECTION 11: FUTURE OBJECTS PERMISSIONS
-- ===================================================================
USE ROLE ACCOUNTADMIN;

-- AR_PROD_RAW_RW - Future Objects in Bronze Layer
GRANT ALL ON FUTURE TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE TASKS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE SEQUENCES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE STAGES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;

-- AR_PROD_TRANS_RW - Future Objects in Silver Layer
GRANT ALL ON FUTURE TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE TASKS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE SEQUENCES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE STAGES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;

-- AR_PROD_CSM_RW - Future Objects in Gold Layer
GRANT ALL ON FUTURE TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE TASKS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE SEQUENCES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE STAGES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;

-- ===================================================================
-- MISSING SECTION 12: READ-ONLY PERMISSIONS FOR RO ROLES
-- ===================================================================

-- AR_PROD_RAW_RO - Read Access to Bronze Layer
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;

-- AR_PROD_TRANS_RO - Read Access to Silver Layer
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;

-- AR_PROD_CSM_RO - Read Access to Gold Layer
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;

-- ===================================================================
-- SECTION : user management
-- ===================================================================
-- GRANT ROLE FR_PROD_DATA_ENGINEER TO USER RSAWANE;
-- GRANT ROLE FR_PROD_DATA_ANALYST TO USER RSAWANE;
-- GRANT ROLE FR_PROD_ETL TO USER RSAWANE;
-- GRANT ROLE FR_PROD_BI TO USER RSAWANE;



-- ===================================================================
-- SECTION 14: added while debugging
-- ===================================================================


USE ROLE securityadmin;
GRANT CREATE DYNAMIC TABLE ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT CREATE DYNAMIC TABLE ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT CREATE DYNAMIC TABLE ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;

GRANT ALL ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RW;
GRANT ALL ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RW;
GRANT ALL ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RW;

GRANT SELECT ON ALL DYNAMIC  TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;

GRANT DATABASE ROLE AR_PROD_RAW_RO TO ROLE FR_PROD_ETL;
GRANT DATABASE ROLE AR_PROD_TRANS_RO TO ROLE FR_PROD_ETL;
GRANT DATABASE ROLE AR_PROD_CSM_RO TO ROLE FR_PROD_ETL;

GRANT DATABASE ROLE AR_PROD_RAW_RO TO ROLE FR_PROD_DATA_ENGINEER;
GRANT DATABASE ROLE AR_PROD_TRANS_RO TO ROLE FR_PROD_DATA_ENGINEER;
GRANT DATABASE ROLE AR_PROD_CSM_RO TO ROLE FR_PROD_DATA_ENGINEER;

-- REVOKE SELECT ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER FROM DATABASE ROLE AR_PROD_TRANS_RW;
-- REVOKE SELECT ON ALL DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD FROM DATABASE ROLE AR_PROD_CSM_RW;
USE ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;

GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE AR_PROD_RAW_RO;
GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE AR_PROD_TRANS_RO;
GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE AR_PROD_CSM_RO;


-- ===================================================================
-- SECTION 15: service user for tableau & ADF
-- ===================================================================
USE ROLE useradmin;

CREATE USER if not exists RSAWANE
 PASSWORD             = 'rsa!d@v@bi^r@!03'
 LOGIN_NAME           = 'RSAWANE'
 DISPLAY_NAME         = 'RSAWANE'
 TYPE = 'LEGACY_SERVICE'
 MUST_CHANGE_PASSWORD =  TRUE;

CREATE USER if not exists ATHAKUR
 PASSWORD             = 'ath!d@v@bi^r@!02'
 LOGIN_NAME           = 'ATHAKUR'
 DISPLAY_NAME         = 'ATHAKUR'
 TYPE = 'LEGACY_SERVICE'
 MUST_CHANGE_PASSWORD =  TRUE;


CREATE USER if not exists RMESHRAM
 PASSWORD             = 'rme!d@v@bi^r@!01'
 LOGIN_NAME           = 'RMESHRAM'
 DISPLAY_NAME         = 'RMESHRAM'
 TYPE = 'LEGACY_SERVICE'
 MUST_CHANGE_PASSWORD =  TRUE;
 
 CREATE USER if not exists SREWATE
 PASSWORD             = 'sre!d@v@bi^r@!04'
 LOGIN_NAME           = 'SREWATE'
 DISPLAY_NAME         = 'SREWATE'
 TYPE = 'LEGACY_SERVICE'
 MUST_CHANGE_PASSWORD =  TRUE;
 
 CREATE USER if not exists KKUMAR
 PASSWORD             = 'kku!d@v@bi^r@!06'
 LOGIN_NAME           = 'KKUMAR'
 DISPLAY_NAME         = 'KKUMAR'
 TYPE = 'LEGACY_SERVICE'
 MUST_CHANGE_PASSWORD =  TRUE;


CREATE USER if not exists FR_PROD_BI_USER
 LOGIN_NAME           = 'FR_PROD_BI_USER'
 DISPLAY_NAME         = 'FR_PROD_BI_USER'
 TYPE = 'SERVICE';

 
 CREATE USER if not exists FR_PROD_ETL_USER
 LOGIN_NAME           = 'FR_PROD_ETL_USER'
 DISPLAY_NAME         = 'FR_PROD_ETL_USER'
 TYPE = 'SERVICE';

 USE ROLE securityadmin;
 
GRANT ROLE FR_PROD_ETL TO USER FR_PROD_ETL_USER;
GRANT ROLE FR_PROD_BI TO USER FR_PROD_BI_USER;

GRANT ROLE FR_PROD_ETL TO USER RSAWANE;
GRANT ROLE FR_PROD_ETL TO USER KKUMAR;
GRANT ROLE FR_PROD_ETL TO USER SREWATE;
GRANT ROLE FR_PROD_ETL TO USER RMESHRAM;
GRANT ROLE FR_PROD_ETL TO USER ATHAKUR;

GRANT ROLE FR_PROD_DATA_ENGINEER TO USER RSAWANE;
GRANT ROLE FR_PROD_DATA_ENGINEER TO USER KKUMAR;
GRANT ROLE FR_PROD_DATA_ENGINEER TO USER SREWATE;
GRANT ROLE FR_PROD_DATA_ENGINEER TO USER RMESHRAM;
GRANT ROLE FR_PROD_DATA_ENGINEER TO USER ATHAKUR;

---------------ADDED WHILE DEBUGGING 22 JULY
USE ROLE SECURITYADMIN;
USE DATABASE trustcab_PROD;

-- Grant USAGE, MONITOR on TRUSTCAB_PROD to RW database roles
GRANT USAGE, MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE TRUSTCAB_PROD.AR_PROD_RAW_RW;
GRANT USAGE, MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE TRUSTCAB_PROD.AR_PROD_TRANS_RW;
GRANT USAGE, MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE TRUSTCAB_PROD.AR_PROD_CSM_RW;


-- Grant USAGE, MONITOR on TRUSTCAB_PROD to RO database roles
GRANT USAGE, MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_BRONZE TO DATABASE ROLE TRUSTCAB_PROD.AR_PROD_RAW_RO;
GRANT USAGE, MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_SILVER TO DATABASE ROLE TRUSTCAB_PROD.AR_PROD_TRANS_RO;
GRANT USAGE, MONITOR ON SCHEMA TRUSTCAB_PROD.SCH_TRUSTCAB_GOLD TO DATABASE ROLE TRUSTCAB_PROD.AR_PROD_CSM_RO;

