data_quality_checks:
  null_checks:
    - table: "BRONZE.FACT_TRIPS"
      columns: ["CITY_ID", "MONTH"]
  
  unique_checks:
    - table: "BRONZE.FACT_TRIPS"
      columns: ["CITY_ID"]
  
  count_checks:
    - table: "BRONZE.FACT_TRIPS"
      min_count: 1