environment: prod
database: TRUSTCAB_PROD
schemas:
  - SCH_TRUSTCAB_BRONZE
  - SCH_TRUSTCAB_SILVER
  - SCH_TRUSTCAB_GOLD
  - CORTEX_DEMO_SCH
  - SCH_TRUSTCAB_AUDIT
warehouse: COMPUTE_WH
role: SYSADMIN