USE DATABASE {DATABASE_NAME};
--silver layer tables
create or replace dynamic table SCH_TRUSTCAB_SILVER.CITY_TARGET_PASSENGER_RATING_DYNAMIC(
	CITY_ID,
	TARGET_AVG_PASSENGER_RATING,
	SOURCE_FILE,
	FILE_ROW_NUM,
	LOAD_TIMESTAMP
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.CITY_TARGET_PASSENGER_RATING;

create or replace dynamic table SCH_TRUSTCAB_SILVER.DIM_CITY_DYNAMIC(
	CITY_ID,
	CITY_NAME,
	SOURCE_FILE,
	FILE_ROW_NUM,
	LOAD_TIMESTAMP
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.DIM_CITY;

create or replace dynamic table SCH_TRUSTCAB_SILVER.DIM_DATE_DYNAMIC(
	DATE,
	START_OF_MONTH,
	MONTH_NAME,
	DAY_TYPE
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.DIM_DATE;

create or replace dynamic table SCH_TRUSTCAB_SILVER.DIM_REPEAT_TRIP_DISTRIBUTION_DYNAMIC(
	MONTH,
	CITY_ID,
	TRIP_COUNT,
	REPEAT_PASSENGER_COUNT,
	SOURCE_FILE,
	FILE_ROW_NUM,
	LOAD_TIMESTAMP
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.DIM_REPEAT_TRIP_DISTRIBUTION;

create or replace dynamic table SCH_TRUSTCAB_SILVER.FACT_PASSENGER_SUMMARY_DYNAMIC(
	MONTH,
	CITY_ID,
	NEW_PASSENGERS,
	REPEAT_PASSENGER,
	TOTAL_PASSENGERS,
	SOURCE_FILE,
	FILE_ROW_NUM,
	LOAD_TIMESTAMP
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.FACT_PASSENGER_SUMMARY;

create or replace dynamic table SCH_TRUSTCAB_SILVER.FACT_TRIPS_DYNAMIC(
	TRIP_ID,
	DATE,
	CITY_ID,
	PASSENGER_TYPE,
	DISTANCE_TRAVELLED_KM,
	FARE_AMOUNT,
	PASSENGER_RATING,
	DRIVER_RATING
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.FACT_TRIPS;

create or replace dynamic table SCH_TRUSTCAB_SILVER.MONTHLY_TARGET_NEW_PASSENGERS_DYNAMIC(
	MONTH,
	CITY_ID,
	TARGET_NEW_PASSENGERS,
	SOURCE_FILE,
	FILE_ROW_NUM,
	LOAD_TIMESTAMP
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.MONTHLY_TARGET_NEW_PASSENGERS;

create or replace dynamic table SCH_TRUSTCAB_SILVER.MONTHLY_TARGET_TRIPS_DYNAMIC(
	MONTH,
	CITY_ID,
	TOTAL_TARGET_TRIPS,
	SOURCE_FILE,
	FILE_ROW_NUM,
	LOAD_TIMESTAMP
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_DEV_DATA_ENGINEER
 as
SELECT * FROM SCH_TRUSTCAB_BRONZE.MONTHLY_TARGET_TRIPS;