USE DATABASE {DATABASE_NAME};

USE SCHEMA SCH_TRUSTCAB_AUDIT;

use role accountadmin;

create or replace tag PII_INFO  allowed_values  'NUMERIC_INFO' , 'STRING_INFO' COMMENT='Tag used for masking sensitive data'
;

create or replace tag SENSITIVITY COMMENT='Tag for classifying sensitive data (e.g., PII, FINANCIAL)'
;

create or replace masking policy SCH_TRUSTCAB_AUDIT.PII_MASK as (VAL NUMBER(38,0)) 
returns NUMBER(38,0) ->
CASE
WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('{DATABASE_NAME}.SCH_TRUSTCAB_AUDIT.PII_INFO') = 'NUMERIC_INFO' AND CURRENT_ROLE() NOT IN ('MASKING_ADMIN','ACCOUNTADMIN') THEN '-1'
ELSE VAL
END
;

create or replace masking policy SCH_TRUSTCAB_AUDIT.PII_STRING_INFO as (VAL VARCHAR) 
returns VARCHAR ->
CASE
WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('{DATABASE_NAME}.SCH_TRUSTCAB_AUDIT.PII_INFO') = 'STRING_INFO' AND CURRENT_ROLE() NOT IN ('MASKING_ADMIN','ACCOUNTADMIN') THEN '**MASKED**'
ELSE VAL
END
;

ALTER TAG {DATABASE_NAME}.SCH_TRUSTCAB_AUDIT.PII_INFO SET MASKING POLICY PII_MASK, MASKING POLICY PII_STRING_INFO;
use role sysadmin;